float:
  euclidean:
  - base_args: {}
    constructor: Scann
    disabled: false
    docker_tag: ann-benchmarks-scann
    module: ann_benchmarks.algorithms.scann
    name: scann
    run_groups:
      # scann1:
      #   args: [[600], [.nan], [2], [squared_l2]]
      #   query_args: [[[20, 140, 0, 0], 
      #                 [35, 240, 0, 0],
      #   ]]
      scann2:
        args: [[2000], [.nan], [4], [squared_l2]]
        query_args: [[
                      # [200, 900, 0, 0, 60, 120],
                      [207, 1100, 0.2, 0, 1, 80],
                    ]]